[package]
name = "open-hardware-monitor"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.7"
open-hardware-monitor-sys = { git = "https://github.com/SpiralP/rust-open-hardware-monitor-sys.git" }
widestring = "0.4.0"
